In [1]:
import os
import pandas as pd
import numpy as np

In [2]:
#%run divvy_download.py

In [3]:
directory = "./extracted_files_test"

dataframes_number = {}
dataframes_divvy = {}
i = 0
j = 0
for root, dirs, files in os.walk(directory):
    for filename in files:
        file_path = os.path.join(root, filename)
        #print(f"File: {file_path}")
        if filename.endswith('tripdata.csv'): #or filename.startswith('Divvy_Trips'):  
            #print(filename)
            try:
                df = pd.read_csv(file_path)
                dataframes_number[i] = df
                i += 1
            except:
                pass
            
       # if filename.startswith('Divvy_Trips'):
       #     #print(filename)           
       #     try:
       #         df = pd.read_csv(file_path)
       #         dataframes_divvy[j] = df
       #         j += 1
       #     except:
       #         pass

In [4]:
df.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,C809ED75D6160B2A,electric_bike,2021-05-30 11:58:15,2021-05-30 12:10:39,NaN,NaN,NaN,NaN,41.90,-87.63,41.89,-87.61,casual
1,DD59FDCE0ACACAF3,electric_bike,2021-05-30 11:29:14,2021-05-30 12:14:09,NaN,NaN,NaN,NaN,41.88,-87.62,41.79,-87.58,casual
2,0AB83CB88C43EFC2,electric_bike,2021-05-30 14:24:01,2021-05-30 14:25:13,NaN,NaN,NaN,NaN,41.92,-87.70,41.92,-87.70,casual
3,7881AC6D39110C60,electric_bike,2021-05-30 14:25:51,2021-05-30 14:41:04,NaN,NaN,NaN,NaN,41.92,-87.70,41.94,-87.69,casual
4,853FA701B4582BAF,electric_bike,2021-05-30 18:15:39,2021-05-30 18:22:32,NaN,NaN,NaN,NaN,41.94,-87.69,41.94,-87.70,casual

In [5]:
def merge_dfs(dataframes):
    merged = dataframes[0]
    for i in range(1,len(dataframes)):
        merged = pd.concat([merged,dataframes[i]], axis=0, ignore_index=True)
    return merged

In [6]:
merged_number = merge_dfs(dataframes_number)

In [7]:
merged_number.to_csv('df_merged.tsv', sep='\t')

In [8]:
df = merged_number

In [9]:
df.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,BD0A6FF6FFF9B921,electric_bike,2020-11-01 13:36:00,2020-11-01 13:45:40,Dearborn St & Erie St,110.0,St. Clair St & Erie St,211.0,41.894177,-87.629127,41.894434,-87.623379,casual
1,96A7A7A4BDE4F82D,electric_bike,2020-11-01 10:03:26,2020-11-01 10:14:45,Franklin St & Illinois St,672.0,Noble St & Milwaukee Ave,29.0,41.890959,-87.635343,41.900675,-87.662480,casual
2,C61526D06582BDC5,electric_bike,2020-11-01 00:34:05,2020-11-01 01:03:06,Lake Shore Dr & Monroe St,76.0,Federal St & Polk St,41.0,41.880983,-87.616754,41.872054,-87.629550,casual
3,E533E89C32080B9E,electric_bike,2020-11-01 00:45:16,2020-11-01 00:54:31,Leavitt St & Chicago Ave,659.0,Stave St & Armitage Ave,185.0,41.895499,-87.682013,41.917744,-87.691392,casual
4,1C9F4EF18C168C60,electric_bike,2020-11-01 15:43:25,2020-11-01 16:16:52,Buckingham Fountain,2.0,Buckingham Fountain,2.0,41.876497,-87.620358,41.876448,-87.620338,casual

In [10]:
temp_df = df
df = temp_df

In [11]:
df.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual
0,BD0A6FF6FFF9B921,electric_bike,2020-11-01 13:36:00,2020-11-01 13:45:40,Dearborn St & Erie St,110.0,St. Clair St & Erie St,211.0,41.894177,-87.629127,41.894434,-87.623379,casual
1,96A7A7A4BDE4F82D,electric_bike,2020-11-01 10:03:26,2020-11-01 10:14:45,Franklin St & Illinois St,672.0,Noble St & Milwaukee Ave,29.0,41.890959,-87.635343,41.900675,-87.662480,casual
2,C61526D06582BDC5,electric_bike,2020-11-01 00:34:05,2020-11-01 01:03:06,Lake Shore Dr & Monroe St,76.0,Federal St & Polk St,41.0,41.880983,-87.616754,41.872054,-87.629550,casual
3,E533E89C32080B9E,electric_bike,2020-11-01 00:45:16,2020-11-01 00:54:31,Leavitt St & Chicago Ave,659.0,Stave St & Armitage Ave,185.0,41.895499,-87.682013,41.917744,-87.691392,casual
4,1C9F4EF18C168C60,electric_bike,2020-11-01 15:43:25,2020-11-01 16:16:52,Buckingham Fountain,2.0,Buckingham Fountain,2.0,41.876497,-87.620358,41.876448,-87.620338,casual

In [12]:
df['started_at'] = pd.to_datetime(df['started_at'])
df['week_temp'] = df['started_at'].dt.to_period('W').astype(str)
df['year_week'] = [df['week_temp'][i].split('/')[0] for i in range(len(df)) ]

In [13]:
#df['started_at'] = pd.to_datetime(df['started_at'])
df['year'] = df['started_at'].dt.year
#df['year_week'] = pd.to_datetime(df['started_at']).dt.strftime('%Y-%W')
#df['year_week'] = pd.to_datetime(df['started_at']).dt.to_period('W')
df['year_month'] = df['started_at'].dt.to_period('M')
df['week'] = df['started_at'].dt.strftime('%W')
df['month'] = df['started_at'].dt.month
#df['week_temp'] = df['started_at'].dt.to_period('W').astype(str)
#df['week'] = [df['week_temp'][i].split('/')[0] for i in range(len(df)) ]
df['season'] = (df['month']-1)//3

In [14]:
df = df[df.rideable_type != 'electric_scooter']

In [15]:
df.loc[df['rideable_type'] == 'docked_bike', 'rideable_type'] = 'classic_bike'

In [16]:

df['rideable_type'] = df['rideable_type'].replace({'classic_bike': 1, 'electric_bike': 2})
df['rideable_type'] = df['rideable_type'].astype(int)

#df['year_week_temp'] = df['started_at'].dt.to_period('W').astype(str)

#df['year_week'] = [df['year_week_temp'][i].split('/')[0] for i in range(len(df))]

/var/folders/qx/bdlxtnn15xg42mxf3d1962000000gn/T/ipykernel_3037/3150884309.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['rideable_type'] = df['rideable_type'].replace({'classic_bike': 1, 'electric_bike': 2})
/var/folders/qx/bdlxtnn15xg42mxf3d1962000000gn/T/ipykernel_3037/3150884309.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['rideable_type'] = df['rideable_type'].astype(int)

In [17]:
df.head()

,ride_id,rideable_type,started_at,ended_at,start_station_name,start_station_id,end_station_name,end_station_id,start_lat,start_lng,end_lat,end_lng,member_casual,week_temp,year_week,year,year_month,week,month,season
0,BD0A6FF6FFF9B921,2,2020-11-01 13:36:00,2020-11-01 13:45:40,Dearborn St & Erie St,110.0,St. Clair St & Erie St,211.0,41.894177,-87.629127,41.894434,-87.623379,casual,2020-10-26/2020-11-01,2020-10-26,2020,2020-11,43,11,3
1,96A7A7A4BDE4F82D,2,2020-11-01 10:03:26,2020-11-01 10:14:45,Franklin St & Illinois St,672.0,Noble St & Milwaukee Ave,29.0,41.890959,-87.635343,41.900675,-87.662480,casual,2020-10-26/2020-11-01,2020-10-26,2020,2020-11,43,11,3
2,C61526D06582BDC5,2,2020-11-01 00:34:05,2020-11-01 01:03:06,Lake Shore Dr & Monroe St,76.0,Federal St & Polk St,41.0,41.880983,-87.616754,41.872054,-87.629550,casual,2020-10-26/2020-11-01,2020-10-26,2020,2020-11,43,11,3
3,E533E89C32080B9E,2,2020-11-01 00:45:16,2020-11-01 00:54:31,Leavitt St & Chicago Ave,659.0,Stave St & Armitage Ave,185.0,41.895499,-87.682013,41.917744,-87.691392,casual,2020-10-26/2020-11-01,2020-10-26,2020,2020-11,43,11,3
4,1C9F4EF18C168C60,2,2020-11-01 15:43:25,2020-11-01 16:16:52,Buckingham Fountain,2.0,Buckingham Fountain,2.0,41.876497,-87.620358,41.876448,-87.620338,casual,2020-10-26/2020-11-01,2020-10-26,2020,2020-11,43,11,3

In [18]:
def make_grouped(df,period):
    df_grouped = df.groupby([f'year_{period}','rideable_type']).agg(
    rides =('ride_id', 'count'),  # Count of 'ride_id'    
    year = ('year','max'),
    month = ('month','max'),
    week = ('week','max'),
    season = ('season','max')
    ).reset_index()
    
    #df_grouped = df_grouped[df_grouped.rideable_type != 'electric_scooter']
    #df_grouped.loc[df_grouped['rideable_type'] == 'docked_bike', 'rideable_type'] = 'classic_bike'

    #df_grouped['rideable_type'] = df_grouped['rideable_type'].replace({'classic_bike': 1, 'electric_bike': 2})
    #df_grouped['rideable_type'] = df_grouped['rideable_type'].astype(int)
            
    df1 = split_tables(df_grouped[df_grouped.rideable_type == 1], period)
    df2 = split_tables(df_grouped[df_grouped.rideable_type == 2], period)
    
    df_full = pd.concat([df1, df2], ignore_index=True)
    df_full = df_full.sort_values(by=f'year_{period}').reset_index(drop=True)
    
    return df_full

In [19]:
def split_tables(df,period):
    df[f'rides_2{period}s_ago'] = df['rides'].shift(2)
    df[f'rides_last{period}'] = df['rides'].shift(1)
    return df

In [ ]:
df_week = make_grouped(df,'week')
df_month = make_grouped(df,'month')

In [21]:
df_week.to_csv('df_week.tsv', sep='\t')
df_month.to_csv('df_month.tsv', sep='\t')

In [2]:
def my_decorator(func):
    def wrapper():
        print('Beginning')
        func()
        print('end')
    return wrapper

@my_decorator        
def my_func():
    print('func itself')
    
my_func()

Beginning
func itself
end